name: Bug Report
description: Report a bug or issue
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please provide as much detail as possible to help us investigate.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the project is affected?
      options:
        - Plugin (Lightweight Edition)
        - Framework (Comprehensive Edition)
        - Documentation
        - Not sure
    validations:
      required: true

  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      description: If using the plugin, which version? (e.g., 1.0.0)
      placeholder: "1.0.0"

  - type: input
    id: claude-code-version
    attributes:
      label: Claude Code Version
      description: Which version of Claude Code are you using?
      placeholder: "Run `claude --version` to find this"

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true

  - type: input
    id: framework-version
    attributes:
      label: Framework Version (if applicable)
      description: If using the full framework, which version?
      placeholder: "5.1.0"

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened? What did you expect to happen?
      placeholder: "A clear description of the bug..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Run command '...'
        2. Observe behavior '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or logs that might help?
