name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We'd love to hear your ideas. Please describe your use case and proposed solution.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the project would this affect?
      options:
        - Plugin (Lightweight Edition)
        - Framework (Comprehensive Edition)
        - Documentation
        - Not sure
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: What problem would this feature solve? What's your use case?
      placeholder: "I'm trying to accomplish... but currently..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like to see this implemented?
      placeholder: "I think we could add..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you considered? What workarounds are you using now?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, examples, or mockups that might help?
