#!/usr/bin/env bash
# fw-contacts.sh — regenerate per-workspace CONTACTS.md views from the contact
# registry at workspaces/kb/company/contacts/ (FEAT-194).
#
# The per-contact record is THE authored home for a person's facts (ADR-008);
# every CONTACTS.md is derived output: stamped with a generated header, safe to
# overwrite, and removed when its workspace no longer has assignments. Edit the
# contact records (Assigned lines), then rerun this script.
#
# --root <dir> (first argument) overrides the repo root — TESTING ONLY.
set -euo pipefail

ROOT=""
if [ "${1:-}" = "--root" ]; then
  ROOT="${2:?--root requires a directory}"
  shift 2
fi
[ $# -eq 0 ] || { echo "Usage: fw-contacts.sh   (no arguments — regenerates every CONTACTS.md)" >&2; exit 1; }

if [ -z "$ROOT" ]; then
  ROOT="$(git rev-parse --show-toplevel)"
fi

REG="$ROOT/workspaces/kb/company/contacts"
if [ ! -d "$REG" ]; then
  {
    echo "Error: no contact registry at workspaces/kb/company/contacts"
    echo "Create the company domain first (fw-new-kb-domain.sh company), then add"
    echo "contact records there from the plugin's templates/records/contact.md."
  } >&2
  exit 1
fi

HDR="<!-- Generated by fw-contacts.sh from workspaces/kb/company/contacts/ — do not edit; edit the contact records and rerun. -->"

# Collect assignments as lines of: workspace|slug|display name|context
ASSIGN="$(mktemp)"
trap 'rm -f "$ASSIGN"' EXIT

for rec in "$REG"/*.md; do
  [ -f "$rec" ] || continue
  base="$(basename "$rec")"
  [ "$base" = "README.md" ] && continue
  slug="${base%.md}"
  name="$(sed -n 's/^# \(.*\)$/\1/p' "$rec" | head -1)"
  [ -n "$name" ] || name="$slug"
  sed -n 's/^\*\*Assigned:\*\*[[:space:]]*//p' "$rec" | while IFS= read -r line; do
    [ -n "$line" ] || continue
    ws="${line%%[[:space:]]*}"
    case "$ws" in __*|"") continue ;; esac   # unfilled template placeholder line
    ctx="${line#"$ws"}"
    ctx="${ctx#"${ctx%%[![:space:]]*}"}"   # ltrim
    ctx="${ctx#—}"; ctx="${ctx#-}"
    ctx="${ctx#"${ctx%%[![:space:]]*}"}"   # ltrim again
    printf '%s|%s|%s|%s\n' "$ws" "$slug" "$name" "$ctx" >> "$ASSIGN"
  done
done

GENERATED=0
SKIPPED=""
WSLIST="$(cut -d'|' -f1 "$ASSIGN" | sort -u)"

for ws in $WSLIST; do
  WSDIR="$ROOT/workspaces/$ws"
  if [ ! -d "$WSDIR" ]; then
    SKIPPED="$SKIPPED $ws"
    continue
  fi
  {
    echo "$HDR"
    echo "# Contacts — $ws"
    echo ""
    grep "^$ws|" "$ASSIGN" | sort -t'|' -k3 | while IFS='|' read -r _ slug name ctx; do
      if [ -n "$ctx" ]; then
        printf -- '- [%s](../kb/company/contacts/%s.md) — %s\n' "$name" "$slug" "$ctx"
      else
        printf -- '- [%s](../kb/company/contacts/%s.md)\n' "$name" "$slug"
      fi
    done
  } > "$WSDIR/CONTACTS.md"
  GENERATED=$((GENERATED + 1))
  echo "Generated: workspaces/$ws/CONTACTS.md"
done

# Remove stale derived views: a generated CONTACTS.md in a workspace that no
# longer has assignments. Only files carrying the generated header are touched.
for f in "$ROOT/workspaces"/*/CONTACTS.md; do
  [ -f "$f" ] || continue
  ws="$(basename "$(dirname "$f")")"
  if ! printf '%s\n' "$WSLIST" | grep -qx "$ws"; then
    if head -1 "$f" | grep -q "Generated by fw-contacts.sh"; then
      rm -f "$f"
      echo "Removed stale: workspaces/$ws/CONTACTS.md"
    fi
  fi
done

echo "Done: $GENERATED workspace view(s) generated."
if [ -n "$SKIPPED" ]; then
  echo "Warning: assignments reference missing workspace(s):$SKIPPED" >&2
fi
