#!/usr/bin/env bash
# fw-contacts.sh — regenerate per-workspace CONTACTS.md views from the contact
# registry at workspaces/kb/company/contacts/ (FEAT-194).
#
# The per-contact record is THE authored home for a person's facts (ADR-008);
# every CONTACTS.md is derived output: stamped with a generated header, safe to
# overwrite, and removed when its workspace no longer has assignments. Edit the
# contact records (Assigned lines), then rerun this script.
#
# --root <dir> (first argument) overrides the repo root — TESTING ONLY.
set -euo pipefail

ROOT=""
if [ "${1:-}" = "--root" ]; then
  ROOT="${2:?--root requires a directory}"
  shift 2
fi

# --check: verify the committed views match what the records generate, changing
# nothing. Exits 1 with a diff if any view is stale. For pre-commit hooks and CI
# — the safety net for records edited outside Claude (ADR-008 derived output).
CHECK=0
if [ "${1:-}" = "--check" ]; then
  CHECK=1
  shift
fi

[ $# -eq 0 ] || { echo "Usage: fw-contacts.sh [--check]   (no arguments — regenerates every CONTACTS.md)" >&2; exit 1; }

if [ -z "$ROOT" ]; then
  ROOT="$(git rev-parse --show-toplevel)"
fi

# --check runs the generator against a throwaway mirror of the repo and diffs
# the result, so there is exactly one implementation of the view format.
if [ "$CHECK" = "1" ]; then
  MIRROR="$(mktemp -d)"
  trap 'rm -rf "$MIRROR"' EXIT
  cp -r "$ROOT/workspaces" "$MIRROR/workspaces"
  [ -d "$ROOT/operations" ] && cp -r "$ROOT/operations" "$MIRROR/operations"
  if ! gen_out="$("$0" --root "$MIRROR" 2>&1)"; then
    printf '%s\n' "$gen_out" >&2
    exit 1
  fi
  STALE=""
  for f in "$MIRROR/workspaces"/*/CONTACTS.md "$MIRROR/operations/CONTACTS.md"; do
    [ -f "$f" ] || continue
    rel="${f#"$MIRROR"/}"
    live="$ROOT/$rel"
    if [ ! -f "$live" ] || ! diff -q "$live" "$f" >/dev/null 2>&1; then
      STALE="$STALE $rel"
      echo "Stale: $rel" >&2
      diff -u "${live:-/dev/null}" "$f" 2>/dev/null | sed 's/^/  /' >&2 || true
    fi
  done
  # A live view with no generated counterpart is stale too (assignment removed).
  for f in "$ROOT/workspaces"/*/CONTACTS.md "$ROOT/operations/CONTACTS.md"; do
    [ -f "$f" ] || continue
    rel="${f#"$ROOT"/}"
    if [ ! -f "$MIRROR/$rel" ] && head -1 "$f" | grep -q "Generated by fw-contacts.sh"; then
      STALE="$STALE $rel"
      echo "Stale: $rel (no longer has assignments; should be removed)" >&2
    fi
  done
  if [ -n "$STALE" ]; then
    echo "" >&2
    echo "CONTACTS.md views are out of date with the contact records." >&2
    echo "Fix: bash \"\$CLAUDE_PLUGIN_ROOT/scripts/fw-contacts.sh\" && git add workspaces/*/CONTACTS.md" >&2
    exit 1
  fi
  echo "OK: all CONTACTS.md views match the contact records."
  exit 0
fi

REG="$ROOT/workspaces/kb/company/contacts"
if [ ! -d "$ROOT/workspaces/kb/company" ]; then
  echo "Error: no company domain in the knowledgebase — create it first: /fw-new-kb-domain company" >&2
  exit 1
fi
if [ ! -d "$REG" ] || ! ls "$REG"/*.md 2>/dev/null | grep -qv '/README\.md$'; then
  echo "Error: no contact records yet in workspaces/kb/company/contacts — add the first one: /fw-contacts <person name>" >&2
  exit 1
fi

HDR="<!-- Generated by fw-contacts.sh from workspaces/kb/company/contacts/ — do not edit; edit the contact records and rerun. -->"

# Collect assignments as lines of: workspace|slug|display name|context
ASSIGN="$(mktemp)"
trap 'rm -f "$ASSIGN"' EXIT

for rec in "$REG"/*.md; do
  [ -f "$rec" ] || continue
  base="$(basename "$rec")"
  [ "$base" = "README.md" ] && continue
  slug="${base%.md}"
  name="$(sed -n 's/^# \(.*\)$/\1/p' "$rec" | head -1)"
  [ -n "$name" ] || name="$slug"
  sed -n 's/^\*\*Assigned:\*\*[[:space:]]*//p' "$rec" | while IFS= read -r line; do
    [ -n "$line" ] || continue
    ws="${line%%[[:space:]]*}"
    case "$ws" in __*|"") continue ;; esac   # unfilled template placeholder line
    case "$(printf '%s' "$ws" | tr '[:upper:]' '[:lower:]')" in unassigned) continue ;; esac   # explicit no-assignment
    ctx="${line#"$ws"}"
    ctx="${ctx#"${ctx%%[![:space:]]*}"}"   # ltrim
    ctx="${ctx#—}"; ctx="${ctx#-}"
    ctx="${ctx#"${ctx%%[![:space:]]*}"}"   # ltrim again
    printf '%s|%s|%s|%s\n' "$ws" "$slug" "$name" "$ctx" >> "$ASSIGN"
  done
done

GENERATED=0
SKIPPED=""
WSLIST="$(cut -d'|' -f1 "$ASSIGN" | sort -u)"

for ws in $WSLIST; do
  # 'operations' is the root queue (TASK-213), not a workspace — different home,
  # different link depth back to the registry.
  if [ "$ws" = "operations" ]; then
    WSDIR="$ROOT/operations"; LNK="../workspaces/kb/company/contacts"
  else
    WSDIR="$ROOT/workspaces/$ws"; LNK="../kb/company/contacts"
  fi
  if [ ! -d "$WSDIR" ]; then
    SKIPPED="$SKIPPED $ws"
    continue
  fi
  {
    echo "$HDR"
    echo "# Contacts — $ws"
    echo ""
    grep "^$ws|" "$ASSIGN" | sort -t'|' -k3 | while IFS='|' read -r _ slug name ctx; do
      if [ -n "$ctx" ]; then
        printf -- '- [%s](%s/%s.md) — %s\n' "$name" "$LNK" "$slug" "$ctx"
      else
        printf -- '- [%s](%s/%s.md)\n' "$name" "$LNK" "$slug"
      fi
    done
  } > "$WSDIR/CONTACTS.md"
  GENERATED=$((GENERATED + 1))
  echo "Generated: ${WSDIR#"$ROOT"/}/CONTACTS.md"
done

# Remove stale derived views: a generated CONTACTS.md in a workspace (or the
# root operations queue) that no longer has assignments. Only files carrying
# the generated header are touched.
for f in "$ROOT/workspaces"/*/CONTACTS.md "$ROOT/operations/CONTACTS.md"; do
  [ -f "$f" ] || continue
  ws="$(basename "$(dirname "$f")")"
  if ! printf '%s\n' "$WSLIST" | grep -qx "$ws"; then
    if head -1 "$f" | grep -q "Generated by fw-contacts.sh"; then
      rm -f "$f"
      echo "Removed stale: ${f#"$ROOT"/}"
    fi
  fi
done

echo "Done: $GENERATED workspace view(s) generated."
if [ -n "$SKIPPED" ]; then
  echo "Warning: assignments reference missing workspace(s):$SKIPPED" >&2
fi
